using System.Diagnostics;
using System.Text;
using WindowsBackupHelper.Core.Checksums;
using WindowsBackupHelper.Core.Exclusions;

namespace WindowsBackupHelper.Core.Tests.Checksums;

/// <summary>
/// Hard compatibility requirement from docs/WINDOWS_HANDOFF.md: a manifest generated by this
/// C# port must be byte-for-byte identical to what checksums_windows_linux.py produces for the
/// same fixture tree, so a manifest from one tool verifies cleanly with the other (including
/// via plain `sha256sum -c` on Linux).
/// </summary>
public sealed class ChecksumManifestGoldenFileTests : IDisposable
{
    private readonly string _fixtureRoot = Path.Combine(Path.GetTempPath(), $"wbh-golden-{Guid.NewGuid():N}");

    public ChecksumManifestGoldenFileTests()
    {
        Directory.CreateDirectory(Path.Combine(_fixtureRoot, "sub", "nested"));
        File.WriteAllText(Path.Combine(_fixtureRoot, "a.txt"), "Hello World\n");
        File.WriteAllBytes(Path.Combine(_fixtureRoot, "sub", "b.bin"), [1, 2, 3, 4, 5, 250, 251, 0]);
        File.WriteAllText(Path.Combine(_fixtureRoot, "sub", "nested", "c.dat"), "Nested file contents for the golden-file test.");

        // Junk that both tools must skip identically.
        File.WriteAllText(Path.Combine(_fixtureRoot, "Thumbs.db"), "junk");
        File.WriteAllText(Path.Combine(_fixtureRoot, "cache.tmp"), "junk");
        File.WriteAllText(Path.Combine(_fixtureRoot, "desktop.ini"), "junk");
    }

    public void Dispose() => Directory.Delete(_fixtureRoot, recursive: true);

    [Fact]
    public async Task Generate_ProducesByteForByteIdenticalManifestTo_ChecksumsWindowsLinuxPy()
    {
        var scriptPath = FindRepoFile("scripts/checksums_windows_linux.py");
        var pythonExe = ResolvePythonExecutable();

        var csharpOutput = Path.Combine(Path.GetTempPath(), $"wbh-golden-cs-{Guid.NewGuid():N}.sha256");
        var pythonOutput = Path.Combine(Path.GetTempPath(), $"wbh-golden-py-{Guid.NewGuid():N}.sha256");

        try
        {
            var service = new ChecksumGenerateService(new DirectoryFileSystemEnumerator(), new Sha256FileHasher());
            var result = await service.GenerateAsync(_fixtureRoot, workers: 2);
            Assert.Empty(result.Errors);
            ChecksumManifest.Write(result.Entries, csharpOutput);

            RunPython(pythonExe, scriptPath, ["generate", _fixtureRoot, "--output", pythonOutput]);

            var csharpBytes = await File.ReadAllBytesAsync(csharpOutput);
            var pythonBytes = await File.ReadAllBytesAsync(pythonOutput);

            if (!csharpBytes.AsSpan().SequenceEqual(pythonBytes))
            {
                Assert.Fail(
                    $"Manifests are not byte-for-byte identical.\n--- Python ---\n{Encoding.UTF8.GetString(pythonBytes)}\n--- C# ---\n{Encoding.UTF8.GetString(csharpBytes)}");
            }
        }
        finally
        {
            File.Delete(csharpOutput);
            File.Delete(pythonOutput);
        }
    }

    private static void RunPython(string pythonExe, string scriptPath, IEnumerable<string> arguments)
    {
        var startInfo = new ProcessStartInfo(pythonExe) { RedirectStandardOutput = true, RedirectStandardError = true, UseShellExecute = false };
        startInfo.ArgumentList.Add(scriptPath);
        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = Process.Start(startInfo) ?? throw new InvalidOperationException($"Failed to start '{pythonExe}'.");
        var stdout = process.StandardOutput.ReadToEnd();
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, $"'{pythonExe} {scriptPath}' exited {process.ExitCode}.\nSTDOUT:\n{stdout}\nSTDERR:\n{stderr}");
    }

    private static string ResolvePythonExecutable()
    {
        foreach (var candidate in new[] { "python", "python3" })
        {
            try
            {
                using var process = Process.Start(new ProcessStartInfo(candidate, "--version")
                {
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                });
                process!.WaitForExit();
                if (process.ExitCode == 0)
                {
                    return candidate;
                }
            }
            catch
            {
                // Try the next candidate.
            }
        }

        throw new InvalidOperationException(
            "No working Python 3 interpreter found (tried 'python', 'python3') — required for the manifest golden-file test.");
    }

    private static string FindRepoFile(string repoRelativePath)
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
        {
            var candidate = Path.Combine(dir.FullName, repoRelativePath);
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }

        throw new FileNotFoundException($"Could not locate '{repoRelativePath}' by walking up from {AppContext.BaseDirectory}.");
    }
}
